dist: trusty
sudo: false

language: cpp

compiler:
- gcc
- clang

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-6
    - g++-6
    - clang
    - cmake

install:
- if [ "$CXX" = "g++" ]; then export CXX="g++-6" CC="gcc-6"; fi

script:
- cd FileSystemHelper && ./compile.sh && cd ..
- cd LinkedMap && ./compile.sh && cd ..
- cd LuaWrapper && ./install_lua.sh && ./compile.sh && cd ..
- cd SimpleTextTemplate && ./compile.sh && cd ..
- cd StatisticsHelper && ./compile.sh && cd ..

after_success:
- cd FileSystemHelper && ./run.sh ./ && cd ..
- cd LinkedMap && ./run.sh && cd ..
- cd LuaWrapper && ./run_sample_program.sh && cd ..
- cd SimpleTextTemplate && ./run.sh && cd ..
- cd StatisticsHelper && ./run.sh && cd ..

branches:
  only:
  - main

os:
- linux
